config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    post 'notes/upload'
    get 'notes/download'
    get 'courses/search'
    get 'courses/teachings'
    get 'courses/show'
    get 'teachings/notes'
    get 'users/show'
  end

  root to: 'basic#course_search'
  get 'login', to: 'basic#login'
  get 'sign_up', to: 'basic#sign_up'
  get 'course', to: 'basic#course_view'
  get 'profile', to: 'basic#user_profile'
  post 'authenticate', to: 'basic#authenticate_user'
  post 'register', to: 'basic#register_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :school
  has_many :teachings

  validates :faculty, presence: true
  validates :number, presence: true
  validates :school, presence: true

  def self.search(query)
    split = query.split(' ')
    name_results = Course.where("name LIKE ?", "%#{query}%")
    if split.length == 2
      course_results = Course.where("faculty LIKE ? AND number LIKE ?", "%#{split[0]}%", "%#{split[1]}%")
    elsif split.length == 1
      course_results = Course.where("faculty LIKE ? OR number LIKE ?", "%#{split[0]}%", "%#{split[0]}%")
    else
      course_results = []
    end
    course_results + name_results
  end
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :teaching

  validates :attachment, presence: true
  validates :teaching, presence: true

  mount_uploader :attachment, AttachmentUploader
end

app/models/school.rb
class School < ApplicationRecord
  has_many :courses
  has_many :teachers
  has_many :terms

  validates :name, presence: true
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teachings
  belongs_to :school

  validates :name, presence: true
  validates :school, presence: true
end

app/models/teaching.rb
class Teaching < ApplicationRecord
  belongs_to :course
  belongs_to :teacher
  belongs_to :term

  has_many :notes

  validates :course, presence: true
  validates :teacher, presence: true
  validates :term, presence: true
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :school

  validates :year, presence: true
  validates :season, presence: true
  validates :school, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password

  validates :username, presence: true, uniqueness: true, length: { :in => 3..20 }
  validates :password, :confirmation => true
  validates :password_confirmation, presence: true, on: :create
  validates_length_of :password, in: 6..20, on: :create

  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if password.present?
      self.encrypted_password = Digest::SHA1.hexdigest(password)
    end
  end

  def clear_password
    self.password = nil
  end

  def authenticate(pass)
    encrypted = Digest::SHA1.hexdigest(pass)
    encrypted == self.encrypted_password
  end
end

app/controllers/api/courses_controller.rb
class Api::CoursesController < ApiController
  def search
    courses = Course.search(params[:query])
    render_success(data: courses.as_json(include: :school))
  end

  def teachings
    course = Course.find(params[:id])
    render_success(data: course.teachings.as_json(include: [:teacher, :term]))
  end

  def show
    course = Course.find(params[:id])
    render_success(data: course.as_json(include: :school))
  end
end

app/controllers/api/notes_controller.rb
class Api::NotesController < ApiController
  def upload
    teaching = Teaching.find(params[:teaching_id])
    note = Note.new(attachment: params[:attachment], teaching: teaching)
    if note.save
      user = current_user
      user.points += 5
      user.save!
      render_success
    else
      render_error("Upload Failed", note.errors.full_messages.first)
    end
  end

  def download
    note = Note.find(params[:id])
    if current_user.points > 0
      user = current_user
      user.points -= 1
      user.save!
      render_success(data: { url: note.attachment_url })
    else
      render_error("Not Enough Points", "The user does not have enough points for this download")
    end
  end
end

app/controllers/api/teachings_controller.rb
class Api::TeachingsController < ApiController
  def notes
    teaching = Teaching.find(params[:id])
    render_success(data: teaching.notes)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApiController
  def show
    user = User.find(params[:id])
    render_success(data: user.as_json(except: [:encrypted_password]))
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  #before_filter :require_user_presence!

  protected

  def render_error(error, message, par={})
    par[:status] ||= 400
    render json: { error: error, msg: message, status: par[:status] }, status: par[:status]
  end

  def render_success(par={})
    par[:status] ||= 200
    data = par[:data] ? { data: par[:data] } : {}
    resp = { status: par[:status] }.merge(data)
    render json: resp, status: par[:status]
  end

  def require_user_presence!
    return true if DEV_MODE
    unless User.exists?(id: session[:user_id])
      render_error("Authentication Error", "User is not signed in")
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  DEV_MODE = true

  protected

  def current_user
    return User.first if DEV_MODE
    if User.exists?(id: session[:user_id])
      User.find(session[:user_id])
    else
      nil
    end
  end

  def require_user_presence!
    return true if DEV_MODE
    unless current_user
      redirect_to login_url
      false
    end
  end
end

app/controllers/basic_controller.rb
class BasicController < ApplicationController

  before_filter :require_user_presence!, only: [:course_search, :course_view, :user_profile]
  before_action :load_user, only: [:course_search, :course_view, :user_profile]

  def login
  end

  def sign_up
  end

  def course_search
  end

  def course_view
  end

  def user_profile
  end

  def authenticate_user
    user = User.find_by_username(params[:username])
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      redirect_to login_url
    end
  end

  def register_user
    user = User.new(username: params[:username], password: params[:password],
                    password_confirmation: params[:password_confirmation])
    if user.save
      session[:user_id] = user.id
      redirect_to root_url
    else
      @user = user
      render :sign_up
    end
  end

  private

  def load_user
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/basic/course_search.html.erb
<html lang="en">
	<head>
	  <title>NoteEx</title>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link href="https://fonts.googleapis.com/css?family=Dosis|Lato" rel="stylesheet">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	</head>
	<body>
		<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
				<a class="navbar-brand" href="#">
					<i class="glyphicon glyphicon-list-alt"></i>
				</a>
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
					<span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse navbar-menubuilder">
					<ul class="nav navbar-nav navbar-right" id="navbar-buttons-list">
						<li><a href="<%= profile_path %>">Profile</a>
						</li>
					</ul>
				</div>
			</div>
			<section class="navbar_coloured_strip light_sea_green_background">
				<div class="container"/>
			</section>	
		</div>
		<div class="container" id="mainContainer">
				<div class="row">
					<div class="col-xs-4">
						<span class="keppel header">Note</span>
						<span class="light_sea_green header">Ex</span>
					</div>
				</div>	
			<div class="row">
				<form>
					<div class="input-group">
						<input type="text" id="searchbar" class="form-control" placeholder="Search">
						<div class="input-group-btn">
						  <button class="btn">
							<i class="glyphicon glyphicon-search"></i>
						  </button>
						</div>
					</div>
				</form>
			</div>
			<div class="row" id="searchResultTemplate">
				<div class="panel panel-default hidden" style="margin:0px">
					<div class="panel-body">result</div>
				</div>
			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script>
			var ready;
			ready = function () {
				var userId = { id : <%= @current_user.id %>}
				$.get("<%= api_users_show_path %>", userId, function (result) {
						var data = result.data;
						
						$( '<li> <a> Points: ' + data.points + '</a></li>' ).appendTo( "#navbar-buttons-list" )
					});
					
				$( "#searchbar" ).on("input", function() {
					$( ".searchResult" ).remove();
					var query = $( "#searchbar" ).val();
					
					if (query != "") {
						var searchJSON = { query : query };
						
						jQuery.get("<%= api_courses_search_path %>", searchJSON, function (result) {
							var data = result.data;
							for (var i = 0; i < data.length; i++) {
								var classObject = data[i];
								var path = "<%= course_path %>" + "?class_id=" + classObject.id;
								
								var clone = $( "#searchResultTemplate" ).clone();
								clone.find( ".panel-body" ).html('<a href="' + path + '">' + stringifyClass(classObject) + '</a>');
								clone.find( ".hidden" ).removeClass("hidden").addClass("shown").addClass("searchResult");
								clone.attr("id", "result" + i);
								clone.appendTo( "#mainContainer" );
							}
						});
					}
				});
			}
			
			function stringifyClass(classObject)
			{
				var string = classObject.faculty + " " + classObject.number + ": " + classObject.name;
				return string;
			}

			$(document).ready(ready);	
		</script>
	</body>
</html>

app/views/basic/course_view.html.erb
<html lang="en">
	<head>
	  <title>NoteEx</title>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <link href="https://fonts.googleapis.com/css?family=Dosis|Lato" rel="stylesheet">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	</head>
	<body>
		<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
			<div class="container-fluid">
				<div class="navbar-header">
				<a class="navbar-brand" href="<%= root_path %>">
					<span class="azure_white small_brand">NoteEx</span>
				</a>
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
					<span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</button>
				</div>
				
				<div class="collapse navbar-collapse navbar-menubuilder">
					<ul class="nav navbar-nav navbar-right" id="navbar-buttons-list">
						<li>
							<%= form_tag("/upload", method: "post", id: "upload_form") do %>
								<label class="btn btn-default btn-file keppel_background btn-navbar hidden" id="uploadLabel">
									Upload <input name="attachment" type="file" style="display: none;" id="upload">
								</label>
							<% end %>
						</li>
						<li><a href="<%= profile_path %>">Profile</a>
						</li>
					</ul>
				</div>
			</div>
			<section class="navbar_coloured_strip  light_sea_green_background">
				<div class="container"/>
			</section>	
		</div>
		<div class="container-fluid" id="mainContainer">
			<div class="row">
				<div class="col-xs-10 shadow_blue header_2 course_name">
				</div>
				<div class="col-xs-2 keppel header_3 course_school" style="text-align: right">
				</div>

			</div>
			<div class="row" style="padding-top:50px">
				<div class="col-xs-3">
					<span class="cadet_grey header_3">Terms</span>
					<ul class="list-group" id="termItemList">
						<li class="list-group-item hidden term-link" id="termItemTemplate"></li>
					</ul>
				</div>
				<div class="col-xs-9">
					<span class="cadet_grey header_3">Notes</span>
					<ul class="list-group" id="noteItemList">
						<li class="list-group-item hidden" id="noteItemTemplate"></li>
					</ul>
				</div>
			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		<script>
			var ready;
			ready = function () {
				var classId = { id : getUrlParameter("class_id")};
				var teachingId = { id : getUrlParameter("teaching_id") };
				var userId = { id : <%= @current_user.id %>}
				
				$.get("<%= api_courses_show_path %>", classId, function (result) {
						var data = result.data;
						$( ".course_name" ).html(stringifyClassName(data));
						$( ".course_school" ).html(data.school.name);
					});
				
				$.get("<%= api_users_show_path %>", userId, function (result) {
					var data = result.data;
					
					$( '<li> <a> Points: ' + data.points + '</a></li>' ).appendTo( "#navbar-buttons-list" )
				});
				
				$.get("<%= api_courses_teachings_path %>", classId, function (result) {
						var data = result.data;
						for (var i = 0; i < data.length; i++) {
							var teaching = data[i];
							teachingId.id = teaching.id;
							var path = "<%= course_path %>" + "?class_id=" + classId.id + "&teaching_id=" + teachingId.id;
							
							var clone = $( "#termItemTemplate" ).clone();
							clone.html('<a href="' + path + '">' + stringifyTerm(teaching.term) + ": " + teaching.teacher.name + '</a>');
							clone.removeClass("hidden").addClass("shown");
							clone.attr("id", "teaching" + i);
							clone.appendTo( "#termItemList" );
						}
					});
					
				if (teachingId.id != null) {
					$( "#uploadLabel" ).removeClass("hidden").addClass("shown");
					$.get("<%= api_teachings_notes_path %>", teachingId, function (result) {
							var data = result.data;
							for (var i = 0; i < data.length; i++) {
								var note = data[i];
								var pathParts = note.attachment.url.split("/");
								var name = pathParts[pathParts.length - 1];
								
								var clone = $( "#noteItemTemplate" ).clone();
								clone.html('<a role="button" class="keppel note-link">' + name + '</a>');
								clone.find("a").attr("id", note.id).click( function() {
									var noteId = { id : this.id };
									$.get("<%= api_notes_download_path %>", noteId, function (result){
										window.open(result.data.url, '_blank');
										window.location.replace(window.location);
									}).fail(function (result) {
										var error = JSON.parse(result.responseText);
										var errorMessageItem = $('<div class="row"> <div class="col-xs-4 error">' + error.error + "!" + '</div></div>');
										errorMessageItem.appendTo( "#noteItem" + noteId.id);
									});
								});
								clone.removeClass("hidden").addClass("shown");
								clone.attr("id", "noteItem" + note.id);
								clone.appendTo( "#noteItemList" );
							}
					});
				}
				$(':file').on('fileselect', function(event, numFiles, label) {
					var attachment = $( "#upload" )[0].files[0];
					var form = document.querySelector("#upload_form");
					
					var fileObject = new FormData(document.querySelector("#upload_form"));
					fileObject.append("attachment", attachment);
					fileObject.append("teaching_id", teachingId.id);
					
					$.ajax({
						url : "<%= api_notes_upload_path %>", 
						type: "POST",
						data: fileObject, 
						cache: false,
						contentType: false,
						processData: false,
						success: function(data) {
							var label = $( "#uploadLabel" );
							var input = label.find("input");

							label.html("Success!");
							label.append(input);
							
							window.location.replace(window.location);
						},
						error : function(error) {
							var label = $( "#uploadLabel" );
							var input = label.find("input");

							label.html("Error");							
							label.append(input);
						}
					});
				});
			
				$(document).on('change', ':file', function() {
					var input = $(this),
					numFiles = input.get(0).files ? input.get(0).files.length : 1,
					label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
					input.trigger('fileselect', [numFiles, label]);
				});
			}
		
		
			function stringifyClassName(classObject)
			{
				return classObject.faculty + " " + classObject.number + ": " + classObject.name;
			}
			
			function stringifyTerm(termObject)
			{
				return termObject.season + " " + termObject.year;
			}
			
			function getUrlParameter(sParam) {
				var sPageURL = decodeURIComponent(window.location.search.substring(1)),
					sURLVariables = sPageURL.split('&'),
					sParameterName,
					i;

				for (i = 0; i < sURLVariables.length; i++) {
					sParameterName = sURLVariables[i].split('=');

					if (sParameterName[0] === sParam) {
						return sParameterName[1] === undefined ? true : sParameterName[1];
					}
				}
			}					
					
			$(document).ready(ready);
		</script>
	</body>
</html>

app/views/basic/login.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NoteEx</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Dosis|Lato" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
	<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">
					<i class="glyphicon glyphicon-list-alt"></i>
				</a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
					<span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse navbar-menubuilder">
				<ul class="nav navbar-nav navbar-right" id="navbar-buttons-list">
					<li><a href="<%= sign_up_path %>">Sign Up</a></li>
				</ul>
			</div>
		</div>
		<section class="navbar_coloured_strip light_sea_green_background">
			<div class="container"/>
		</section>	
	</div>
	<div class="container">
		<div class="row">
			<div class="col-xs-4">
				<span class="keppel header">Note</span>
				<span class="light_sea_green header">Ex</span>
			</div>
		</div>	
		<div class="form-signin center-block">
			<h2 class="form-signin-heading">Login</h2>
			<div class="row">
				<div class="col-sm-6">
					<%= form_tag(authenticate_path, method: "post") do %>
					Username: <input type="text" name="username" class="form-control" required autofocus> </br>
					Password: <input type="password" name="password" class="form-control" required> </br>
					<%= submit_tag "Login", class: "btn btn-lg btn-success btn-block" %>

					<!-- Display error message -->
					<% if @user && @user.errors.any? %>
					<ul class="error-list">
						<% @user.errors.full_messages.each do |error_message| %>
						<li><%= error_message %></li>
						<% end %>
					</ul>
					<% end %>
					<% end %>	
				</div>
				<div class="col-sm-1">
				</div>
				<div class="col-sm-3 text-center">
					<br/><br/><br/> or
					<a href="<%= sign_up_path %>" class="btn btn-lg btn-default btn-block">
						<span class="glyphicon glyphicon-user"></span> Sign Up 
					</a>
				</div>				
			</div>
		</div>
	</body>
	</html>

app/views/basic/sign_up.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NoteEx</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Dosis|Lato" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
	<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="#">
					<i class="glyphicon glyphicon-list-alt"></i>
				</a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder">
					<span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse navbar-menubuilder">
				<ul class="nav navbar-nav navbar-right" id="navbar-buttons-list">
					<li><a href="<%= login_path %>">Login</a>
					</li>
				</ul>
			</div>
		</div>
		<section class="navbar_coloured_strip light_sea_green_background">
			<div class="container"/>
		</section>	
	</div>
	<div class="container">
		<div class="row">
			<div class="col-xs-4">
				<span class="keppel header">Note</span>
				<span class="light_sea_green header">Ex</span>
			</div>
		</div>
		<div class="form-signin center-block">
			<h2 class="form-signin-heading">Sign Up</h2>
			<div class="row">
				<div class="col-sm-6">
					<form action="<%= register_path %>" method="POST">
						<%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

						Username: <input type="text" name="username" class="form-control" required autofocus> </br>
						Password: <input type="password" name="password" class="form-control" required> </br>
						Confirmation: <input type="password" name="password_confirmation" class="form-control" required> </br>
						<button type="submit" class="btn btn-lg btn-success btn-block">Sign Up</button>

						<!-- Display error message -->
						<% if @user && @user.errors.any? %>
						<ul class="error-list">
							<% @user.errors.full_messages.each do |error_message| %>
							<li><%= error_message %></li>
							<% end %>
						</ul>
						<% end %>
					</form>
				</div>
				<div class="col-sm-1">
				</div>
				<div class="col-sm-3 text-center">
					<br/><br/><br/> or
					<a href="<%= login_path %>" class="btn btn-lg btn-default btn-block">
						<span class="glyphicon glyphicon-user"></span> Login 
					</a>
				</div>	
			</div>
		</div>	
	</div>
</body>
</html>

app/views/basic/user_profile.html.erb
<h1>Basic#user_profile</h1>
<p>Find me in app/views/basic/user_profile.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteEx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>